#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Oct 11, 2019 02:15:29 PM IST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+385+135
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    text $top.tex44 \
        -background white -font TkTextFont -foreground black -height 44 \
        -highlightcolor black -insertbackground black \
        -selectbackground #c4c4c4 -selectforeground black -width 416 \
        -wrap word 
    .top42.tex44 configure -font "TkTextFont"
    .top42.tex44 insert end text
    vTcl:DefineAlias "$top.tex44" "Text1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Search 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can46 \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -closeenough 1.0 \
        -height 171 -insertbackground black -relief ridge \
        -selectbackground #c4c4c4 -selectforeground black -width 431 
    vTcl:DefineAlias "$top.can46" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.can46
    listbox $site_3_0.lis48 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -height 146 -width 414 
    .top42.can46.lis48 configure -font "TkFixedFont"
    .top42.can46.lis48 insert end text
    vTcl:DefineAlias "$site_3_0.lis48" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lis48 \
        -in $site_3_0 -x 10 -y 10 -width 414 -relwidth 0 -height 146 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tex44 \
        -in $top -x 80 -y 70 -width 416 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 420 -y 150 -anchor nw -bordermode ignore 
    place $top.can46 \
        -in $top -x 70 -y 220 -width 431 -relwidth 0 -height 171 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

