#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Oct 11, 2019 02:15:24 PM IST  platform: Linux

import sys
import engine
from engine import query

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import dwm_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    dwm_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    dwm_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None



class Toplevel1:
    
     
    
    def retreive_input(self):
        new_text = self.Text1.get("1.0","end-1c")
        self.q_result = query(new_text)
        print(self.q_result)
        i=1
        if self.flag == 2:
            self.Listbox1.delete(0, tk.END)
            self.flag=1
        else:
            self.flag=2
        for result in self.q_result:
            self.Listbox1.insert(i,result)
            i=i+1
       
    def clear_box(self):
        self.Listbox1.delete(0, tk.END)
       
       
        
        
        
    def __init__(self, top=None):
        self.flag = 1
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family FreeSerif -size 16 -weight bold -slant roman "  \
             "-underline 0 -overstrike 0"
        font10 = "-family {DejaVu Sans} -size 10 -weight bold -slant "  \
             "roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans} -size 11 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        top.geometry("600x450+385+135")
        top.title("Search Engine")

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.133, rely=0.156, relheight=0.098, relwidth=0.693)

        self.Text1.configure(background="white")
        self.Text1.configure(font=font11)
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(spacing1="6")
        self.Text1.configure(wrap="word")
        

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.7, rely=0.333, height=31, width=72)
        self.Button1.configure(text='''Search''')
        self.Button1.configure(command=self.retreive_input)
        self.Button1.configure(font=font10)
        
        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.117, rely=0.889, height=31, width=431)
        self.Button2.configure(text='''Clear''')
        self.Button2.configure(command=self.clear_box)
        self.Button1.configure(font=font10)

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.117, rely=0.489, relheight=0.38
                , relwidth=0.718)
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#c4c4c4")

        self.Listbox1 = tk.Listbox(self.Canvas1)
        self.Listbox1.place(relx=0.023, rely=0.058, relheight=0.854
               , relwidth=0.961)
        self.Listbox1.configure(background="#d8ffa6")
        self.Listbox1.configure(font=font9)
        self.Listbox1.configure(highlightbackground="#0a2625")
        self.Listbox1.configure(highlightcolor="#c6b64b")
        self.Listbox1.configure(selectbackground="#3ac19d")
        self.Listbox1.configure(selectborderwidth="10")
        self.Listbox1.configure(selectforeground="#d3d3d3")
         
    

if __name__ == '__main__':
    vp_start_gui()





